# Generated by Django 5.1.3 on 2025-01-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_location_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Account Balance'),
        ),
    ]
